### ISSUE TITLE
pip和源码安装都提示setup.py中libraries变量未初始化

### ISSUE THREAD

**Issue by wangpenghehe** [vnpy/vnpy_tora#25]
这个问题会在2023.9.5以上版本出现

python版本号： 3.10.11
setuptools: Version: 70.0.0
OS: MacBook Pro M2
错误信息：
Collecting vnpy_tora
Using cached vnpy_tora-2024.3.22.tar.gz (2.6 MB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/private/var/folders/37/6p9sw7kd5wxby_wynmm5y4g40000gn/T/pip-install-38kpzmdv/vnpy-tora_0f54fa3e45d54089a4396a4395d9ffac/setup.py", line 86, in
ext_modules=get_ext_modules(),
File "/private/var/folders/37/6p9sw7kd5wxby_wynmm5y4g40000gn/T/pip-install-38kpzmdv/vnpy-tora_0f54fa3e45d54089a4396a4395d9ffac/setup.py", line 44, in get_ext_modules
libraries=libraries,
UnboundLocalError: local variable 'libraries' referenced before assignment
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by noranhe** [comment]
vnpy_tora没有提供mac支持
